# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    match(
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      type: "appstore",
      readonly: is_ci,
      keychain_password: ENV["MATCH_PASSWORD"]
    )
    increment_build_number(xcodeproj: "Kantan-Manga.xcodeproj")
    build_app(workspace: "Kantan-Manga.xcworkspace", scheme: "MangaReader")
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APPSTORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APPSTORE_CONNECT_API_KEY"]
    )
    upload_to_testflight
  end
end
